# Generated by Django 5.2 on 2025-05-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wells", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellBoundaries",
            fields=[
                (
                    "well",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="boundaries",
                        serialize=False,
                        to="wells.well",
                    ),
                ),
                ("start_ms", models.BigIntegerField(blank=True, null=True)),
                ("end_ms", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
